version: 1.5.0.{build}-beta
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: >-
    powershell .\install-android-sdk.ps1

    powershell .\build.ps1 -Target Default -Verbosity diagnostic
artifacts:
- path: ./build/nuget/*.nupkg
  name: NuGet