version: 2.0.0.{build}-beta
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- ps: .\bootbuild.ps1
artifacts:
- path: ./build/nuget/*.nupkg
  name: NuGet